version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

# We only would want to update to tagged versions, but Dependabot does not
# support that feature yet. See https://github.com/dependabot/dependabot-core/issues/1639
#  - package-ecosystem: "gitsubmodule"
#    directory: "/"
#    schedule:
#      interval: "monthly"
