#
# Docker file for Syntalos Tests on Debian
#
FROM debian:bullseye

# prepare
RUN apt-get update -qq
RUN mkdir -p /build/ci/

# FIXME: Temporary build fix while Debian is in a Python transition
RUN apt-get install -yq --no-install-recommends libpython3.9-dev

# install build dependencies
COPY install-deps-deb.sh /build/ci/
RUN chmod +x /build/ci/install-deps-deb.sh && /build/ci/install-deps-deb.sh

# build & install 3rd-party libraries
COPY make-install-3rdparty.sh /build/ci/
RUN chmod +x /build/ci/make-install-3rdparty.sh && /build/ci/make-install-3rdparty.sh
RUN rm -rf /build/ci/

# finish
WORKDIR /build
