#
# Docker file for Syntalos CI on Debian (stable)
#
FROM debian:trixie

# add Syntalos package repo
RUN apt-get update -qq && apt-get install -y --no-install-recommends curl ca-certificates
RUN curl -fsSL https://syntalos.org/setup/setup-syntalos-repo.sh | sh

# prepare
RUN apt-get update -qq
RUN mkdir -p /build/ci/

# install build dependencies
COPY install-deps-deb.sh /build/ci/
RUN chmod +x /build/ci/install-deps-deb.sh && /build/ci/install-deps-deb.sh

# install extra dependencies
COPY install-deps-deb-extra.sh /build/ci/
RUN chmod +x /build/ci/install-deps-deb-extra.sh && /build/ci/install-deps-deb-extra.sh
RUN rm -rf /build/ci/

# finish
WORKDIR /build
