[syntalos_module]
type = "python"

name = "DeepLabCut Live"
description = "Run DeepLabCut on a live video stream"
icon = "dlc-logo.png"

categories = ['processing']
features = ['show-settings']

main = "dlc-live.py"
use_venv = true

