# Startup .ini file for bypassing GUI startup dialog
# To use this file, pass the filename as a command-line argument when running RHX
# For example, "IntanRHX --settings=startup.ini"

# This feature is designed to streamline automation and limit RHX dialog boxes, so
# if a valid key-value pair is not provided, its default will be used silently;
# be sure to verify that these settings are taking effect in the software, as a typo
# will just result in a default value being used.

# Opal Kelly device serial number as listed in startup dialog
# Note: this is not the number on the back of the Intan controller
# DEFAULT: first controller detected (top of table in startup dialog)
device_serial=224800130O

# Sample rate in Hertz
# Valid values for RHD only: 1000, 1250, 1500, 2000, 2500, 3000, 3333, 4000, 5000, 6250, 8000, 10000, 12500, 15000
# Valid values for both RHD and RHS: 20000, 25000, 30000
# DEFAULT: 20000 Hz for RHD, 30000 Hz for RHS
sample_rate_hz=20000

# Stim step size in microAmps
# Ignored for non-RHS controllers
# Valid values: 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2, 5, 10
# DEFAULT: 0.1
stim_step_size_ua=0.1