name: Build Test

on: [push, pull_request, workflow_call]

jobs:
  build-test:
    name: ${{ matrix.display_name }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: debian-stable
            display_name: Debian Stable
            suite: trixie
            components: main
            runner: ubuntu-latest
          - id: debian-stable-arm64
            display_name: Debian Stable (arm64)
            suite: trixie
            components: main
            runner: ubuntu-24.04-arm
          - runner: ubuntu-latest
            id: debian-testing
            display_name: Debian Testing
            suite: testing
            components: main
          - id: ubuntu-lts
            display_name: Ubuntu LTS
            suite: resolute
            components: main universe
            runner: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Create Build Environment
      uses: ximion/debspawn-action/setup@v1
      with:
        name: ci-${{ matrix.id }}
        suite: ${{ matrix.suite }}
        components: ${{ matrix.components }}
        cache-suffix: 'ci'
        packages: >-
          ca-certificates
          curl
          git
        script: |
          # Setup Syntalos APT Repository
          curl -fsSL https://syntalos.org/setup/setup-syntalos-repo.sh | sh

          # install build dependencies
          ./tests/ci/install-deps-deb.sh

          # install extra dependencies
          ./tests/ci/install-deps-deb-extra.sh

    - name: Build & Test
      uses: ximion/debspawn-action/run@v1
      with:
        name: ci-${{ matrix.id }}
        suite: ${{ matrix.suite }}
        root: false
        summary: "Build & Test Syntalos on ${{ matrix.display_name }}"
        commands: |
          CC=gcc CXX=g++ ./tests/ci/build-and-test.sh
